import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import TopNavBar from '@/components/NavBar/TopNavBar/TopNavBar'
import SideNavBar from '@/components/NavBar/SideNavBar/SideNavBar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Food Network',
  description: 'Generated by Food Network',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
<div>
<div>
  <TopNavBar></TopNavBar>
</div>
<div className='flex'>
  <SideNavBar></SideNavBar>
  <body className={inter.className}>{children}</body>
</div>
</div> 
  )
}
